#!/bin/bash

set -ex

svg="logo.svg"

size=(16 32 24 48)

out="$(mkdir out)"

echo Making bitmaps from your svg...

for i in ${size[@]}; do
  inkscape $svg --export-filename="out/$i.png" -w $i -h $i
done

echo Compressing...

pngquant -f --ext .png out/*.png --posterize 4 --speed 1 --nofs

echo Converting to favicon.ico...

convert "out/*.png" favicon.ico

echo Making Apple Touch
inkscape $svg --export-filename="logo192.png" -w 192 -h 192

echo Compressing Apple Touch
pngquant -f --ext .png logo192.png --posterize 4 --speed 1 --nofs

# Clean-up
rm -rf "out/"

echo Done
